### ISSUE TITLE
rename_template.rb crashes if git remote URL doesn't end with .git

### ISSUE THREAD

**Issue by powder** [mattbrictson/gem#150]
```
% bundle exec ruby rename_template.rb
>>>> git remote -v
>>>> git remote get-url origin
rename_template.rb:198:in `read_git_data': undefined method `split' for nil:NilClass (NoMethodError)

    origin_repo_name: origin_repo_path.split("/").last,
                                      ^^^^^^
        from rename_template.rb:11:in `main'
        from rename_template.rb:253:in `<main>'

```

This is because it's expecting .git at the end of the output, which will not always be the case for a remote.

I fixed it with the following single character change, making the last bit matching git optional.  That said.  I don't know regex very well, and this fixed it for me.  I am curious to know if this is the correct fix.

```
line 193:   origin_repo_path = origin_url[%r{[:/]([^/]+/[^/]+)(?:\.git)?$}, 1]
```

**Comment by mattbrictson** [comment]
Nice find! I guess my git remotes have always ended with `.git`, so I missed this bug.

In terms of the fix, I think yours is halfway there. The `?` you added will make the trailing `.git` part optional, but the `+` wildcard earlier in the expression is "greedy" and therefore match it instead.

You can see in this example:

```ruby
origin_url = "https://github.com/mattbrictson/gem.git"
origin_url[%r{[:/]([^/]+/[^/]+)(?:\.git)?$}, 1]
# => "mattbrictson/gem.git"
```

The solution is to change the `+` to `+?`, which makes it "non-greedy".

```ruby
%r{[:/]([^/]+/[^/]+?)(?:\.git)?$}
#                  ^ non-greedy qualifier
```

[MDN explanation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#quantifiers):

> `x?`
If used immediately after any of the quantifiers `*`, `+`, `?`, or `{}`, makes the quantifier non-greedy (matching the minimum number of times), as opposed to the default, which is greedy (matching the maximum number of times).

Now it works for both `.git` and non-`.git` URLs:

```ruby
origin_url = "https://github.com/mattbrictson/gem.git"
origin_url[%r{[:/]([^/]+/[^/]+?)(?:\.git)?$}, 1]
# => "mattbrictson/gem"

origin_url = "https://github.com/mattbrictson/gem"
origin_url[%r{[:/]([^/]+/[^/]+?)(?:\.git)?$}, 1]
# => "mattbrictson/gem"
```

The regex still makes some assumptions about how the URL is structured, so I think an additional safety check would be a good idea. Maybe change this line to handle the case where `origin_repo_path` is `nil`, just in case:

```ruby
origin_repo_name: origin_repo_path && origin_repo_path.split("/").last,
```

Would you like to open a PR so you can get credit as a contributor?

**Comment by powder** [comment]
Sure, I can take care of that, apologies for the massive delay in response time!
